if("${ARGS}" MATCHES "^libxmp;")
    set(z_vcpkg_libxmp_root "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/libxmp")
    include("${z_vcpkg_libxmp_root}/libxmp-config.cmake")
    include("${z_vcpkg_libxmp_root}/libxmp-config-version.cmake" OPTIONAL)

    if(TARGET libxmp::xmp_shared OR TARGET libxmp::xmp_static)
        set(libxmp_FOUND TRUE)
    else()
        set(libxmp_FOUND FALSE)
    endif()

    unset(z_vcpkg_libxmp_root)
else()
    _find_package(${ARGS})
endif()
